image:
  repository: hoainhan18041997/node-monitoring
  tag: fd447cec3a7a305cf44ba6a33231a0e2fbdafdd2

service:
  port: 3000

ingress:
  enabled: true
  host: node-monitoring.example.com
namespace:
  name: node-monitoring-namespace

imagePullSecrets:
  - name: monitoring-node-regcred