image:
  repository: hoainhan18041997/node-monitoring
  tag: 36a80d1e7d3c2b7ef0dd4a1f1349940c5ef1a90f

service:
  port: 3000

ingress:
  enabled: true
  host: node-monitoring.example.com
namespace:
  name: node-monitoring-namespace

imagePullSecrets:
  - name: monitoring-node-regcred