apiVersion: v1
kind: Service
metadata:
  name: monitoring-node-service
  namespace: {{.Values.namespace.name}}
  labels:
    app: monitoring-node-service
spec:
  selector:
    app: monitoring-node
  ports:
    - port: 80
      targetPort: 3000
